### ISSUE TITLE
FifthRef = KeyReference?

### ISSUE THREAD

**Issue by feesh96** [MegaArman/MusicXMLResearch#3]
Very minor issue, just testing out the issue system here.

@MegaArman 
Is the const *fifthsRef* just the reference guide for the keys? It looks like in MusicXML, before each key change, it has a `<key>` element with a `<fifths>` element embedded, and the `<fifths>` element determines the key by the circle of fifths...

`<key>

          <fifths>-2</fifths>
          <mode>major</mode>

 </key>`

If this is true, would it be better to name it *keysRef* instead? I'm going to need to use the keys reference to determine amount of accidentals, and I was just thinking *keysRef* would be an easier to understand name. Thought it would be an easy issue to test issue submissions with.

Also, I noticed that in *getKeySignatures()* you tested to see if the new key was the same as the old-

```
if (key === "fifths")
      {
        let newKeySig = fifthsRef[value];
        let shouldPush = true;

        for (let oldKeySig of keySignatures) //avoid duplicates
        {
          if (newKeySig === oldKeySig)
          {
            shouldPush = false;
          }
        }

        if (shouldPush) keySignatures.push(newKeySig);
      }

```
- should we also test for '<mode>' as well, as in: `<mode>major</mode>`?

Well, this was fun. Hope I didn't annoy y'all too much with this :)

**Comment by MegaArman** [comment]
Hmm.. Good observations. I named it fifthsRef because it is using the circle of fifths to reference the key and the xml tag is "fifths", but I can see how that variable name is lacking. I think a more descriptive name would be fifthToKey and pitchRef could be pitchToMidiNum. That way when we see fifthToKey[value] we know the value must be a fifth (so it's essentially more like a function call).

should we also test for '' as well, as in: <mode>major</mode>?

^ In getKeySignatures()? I don't think so as someone may just want to know how many sharps or flats they'll have to play and might not care about the mode. In a function like getKeysAndModes we'd want that check for duplication to avoid a result like [C Major, A Minor, C Major] as that should just be represented as [C Major, A Minor].... That poses a new question - how should the user determine how many key changes there are? That's for a separate issue however.

Well, this was fun. Hope I didn't annoy y'all too much with this :)

^You're always welcome to raise issues if you're confused by something and think it could be improved! It's a free means of book keeping - essentially we don't need an FAQ because we have an issue board.

**Comment by MegaArman** [comment]
variable renames in recent commit
